"""fix_invoices_schema

Revision ID: 6807ae4b8cf8
Revises: 0a476b207df5
Create Date: 2026-07-02 14:53:30.469658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6807ae4b8cf8'
down_revision: Union[str, None] = '0a476b207df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('invoices', 'due_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_column('invoices', 'payment_method')
    op.drop_column('invoices', 'issue_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('issue_date', sa.DATE(), nullable=False))
    op.add_column('invoices', sa.Column('payment_method', mysql.VARCHAR(length=50), nullable=True))
    op.alter_column('invoices', 'due_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('invoices', 'created_at')
    # ### end Alembic commands ###
