"""se_agrego_billing_and_user_API

Revision ID: e46c54a47c82
Revises: 0a476b207df5
Create Date: 2026-06-25 21:06:28.597450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e46c54a47c82'
down_revision: Union[str, None] = '0a476b207df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
